#!/bin/bash 
# specify the QP folder 
QP=$QP_ROOT
# sourcing the quantum_package.rc file
. ${QP}/quantum_package.rc


ezfio=$1
ezfio=${ezfio%/}
nstate=`cat $ezfio/determinants/n_states`

for i in `seq 1 $nstate`
 do
 echo $i 
 state=${ezfio}_state_$i
 cp -r $ezfio $state 
 qp_edit -s $i $state 
 qp set_file $state 
 qp set two_body_dm ontop_approx True 
 qp set two_body_dm thr_ontop_approx 0.00001
 qp set dft_mu_of_r ci_threshold 0.0000001 
 qp_run truncate_wf_spin_no_H $state 
 qp_run all_mu_of_r_corrections_md $state | tee ${state}.DFT.out 
done
