#!/bin/bash                                                                                                                                  
QP_ROOT=~/programs/qp2/
source ${QP_ROOT}/quantum_package.rc

#### Assumes that an "xyz" file exists for H2 
file_xyz=$1.xyz
basis=$2
charge=$3

ezfio=$1


rm -rf $ezfio

#start with a RHF calculation
qp create_ezfio -b $basis -o $ezfio $file_xyz -c $charge
qp run scf | tee ${ezfio}.scf.out
qp run fci | tee ${ezfio}.fci.out
qp set mu_of_r mu_of_r_potential cas_ful
qp run basis_correction | tee ${ezfio}.DFT.out

qp run write_eff_basis_ints | tee ${ezfio}.eff_ints_1_out
qp run diagonalize_h | tee ${ezfio}.diag_h_1_out

qp run write_eff_basis_ints | tee ${ezfio}.eff_ints_2_out
qp run diagonalize_h | tee ${ezfio}.diag_h_2_out

qp run write_eff_basis_ints | tee ${ezfio}.eff_ints_3_out
qp run diagonalize_h | tee ${ezfio}.diag_h_3_out                      

qp run write_eff_basis_ints | tee ${ezfio}.eff_ints_4_out
qp run diagonalize_h | tee ${ezfio}.diag_h_4_out

qp run write_eff_basis_ints | tee ${ezfio}.eff_ints_5_out
qp run diagonalize_h | tee ${ezfio}.diag_h_5_out                      
