#!/bin/bash                                                                                                                                  
QP_ROOT=~/programs/qp2/
source ${QP_ROOT}/quantum_package.rc

#----------------------------------------------
# SCRIPT 1/2
# NON-SCF DFT(SU-PBE-OT and PBE-UEG)/WFT Basis-correction
# FCI calculations before basis-corrections calculations
# System He
# Remark : Correlation energy is null whatever DFT approximation used
#----------------------------------------------

#### Assumes that an "xyz" file exists for H2 
file_xyz=He.xyz
#basis="cc-pvdz cc-pvtz cc-pvqz cc-pv5z"
basis="cc-pvdz"
ezfio=He
 rm -rf $ezfio

for b in $basis
 do
  mkdir ${b}
  cp ${file_xyz} ${b}/
  cd ${b}
  rm -rf $ezfio

  #start with a RHF calculation
  qp create_ezfio -b $b -o $ezfio $file_xyz 
  qp run scf 
  qp run fci

  #define the main options : mu, functional, number of determinants, max pt2 and reading or not two-elec integrals (to save time)
  mu=cas_ful 
  ndet=1000
  pt2=0.
  readint=False
  fun=su_pbe_ot
  threshold=0.000000001

  rm -rf ${b}_${fun}
  mkdir ${b}_${fun}
  cp -r $ezfio ${b}_${fun}/

  cd ${b}_${fun}

  ## run the basis_corr script
  qp_sc_basis_corr  -m $mu  -f $fun -p $pt2 -t $threshold $ezfio 

  cd ../

  mu=cas_ful
  ndet=1000
  pt2=0.
  readint=False
  fun=pbe_ueg
  threshold=0.000000001
 
  rm -rf ${b}_${fun}
  mkdir ${b}_${fun}
  cp -r $ezfio ${b}_${fun}/

  cd ${b}_${fun}
  
  ## run the basis_corr script
  qp_sc_basis_corr  -m $mu  -f $fun -p $pt2 -t $threshold $ezfio
  cd ../..
 done
