#!/bin/bash                                                                                                                                  
QP_ROOT=~/programs/qp2/
source ${QP_ROOT}/quantum_package.rc

#----------------------------------------------
# SCRIPT 2/2
# NON-SCF DFT(SU-PBE-OT)/WFT Basis-correction
# FCI calculations before basis-corrections calculations
# System He
# Remark : Correlation energy is null whatever DFT approximation used
#----------------------------------------------

#### Assumes that an "xyz" file exists for H2 
file_xyz=He.xyz
basis="cc-pvdz cc-pvtz cc-pvqz cc-pv5z"
ezfio=He
 rm -rf $ezfio

for b in $basis
 do
  mkdir ${b}
  cp ${file_xyz} ${b}/
  cd ${b}
  rm -rf $ezfio

  #start with a RHF calculation
  qp create_ezfio -b $b -o $ezfio $file_xyz 
  qp run scf 
  qp run fci

  #define the main options : mu, functional, number of determinants, max pt2 and reading or not two-elec integrals (to save time)
  #rm -rf ${b}_${fun}
  #mkdir ${b}_${fun}
  #cp -r $ezfio ${b}_${fun}/

  cd ${b}
  rm -rf ${b}
  mkdir ${b}
  cp -r $ezfio ${b}

  cd ${b}
  qp set mu_of_r mu_of_r_potential cas_ful
  qp run write_eff_basis_ints | tee write_eff_basis_He.out 
  
  cd ../
 
#  rm -rf ${b}_${fun}
#  mkdir ${b}_${fun}
#  cp -r $ezfio ${b}_${fun}/

#  cd ${b}_${fun}
  
#  ## run the basis_corr script
# qp set mu_of_r mu_of_r_potential cas_ful
#  qp run write_eff_basis_ints 
#  cd ../..
 done
